# Generated by Django 5.1.7 on 2025-04-13 10:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof')], default='Mr', max_length=10)),
                ('first_name', models.CharField(default='Default First Name', max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(default='Default Surname', max_length=50)),
                ('address_line_1', models.CharField(default='Default Address', max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(default='Default City', max_length=50)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('postcode', models.CharField(default='00000', max_length=10)),
                ('country', models.CharField(default='United Kingdom', max_length=50)),
                ('client_email', models.EmailField(max_length=254, unique=True)),
                ('client_mobile', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_payroll_number', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof')], default='Mr', max_length=10)),
                ('first_name', models.CharField(default='Default First Name', max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(default='Default Surname', max_length=50)),
                ('employee_mobile', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('Painter', 'Painter'), ('Joiner', 'Joiner'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Manager', 'Manager')], default='Painter', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCatalogue',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('service_description', models.TextField()),
                ('service_hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAppointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField()),
                ('appointment_duration', models.PositiveIntegerField()),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.servicecatalogue')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceRow',
            fields=[
                ('invoice_row_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.clientappointment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.servicecatalogue')),
            ],
            options={
                'unique_together': {('employee', 'service')},
            },
        ),
    ]
