# Generated by Django 5.1.7 on 2025-03-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Service_Catalogue',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='discount',
            new_name='invoice_cost',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='final_total',
            new_name='invoice_discount',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='total_cost',
            new_name='invoice_total',
        ),
    ]
